name: Change Request
description: Modify or deprecate an existing entry
title: "change: <id>"
labels: ["change"]
body:
  - type: input
    id: id
    attributes:
      label: Entry ID
      description: gib:<domain>:<slug>:v<version>
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
    validations:
      required: true

