name: Auto-add issues & PRs to Co Stack

on:
  issues:
    types: [opened, transferred, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project via GraphQL
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   # PAT with repo + project scopes
          OWNER: rickballard
          PROJ_NUM: 3
          EVENT: ${{ github.event_name }}
          ISSUE_NODE: ${{ github.event.issue.node_id }}
          PR_NODE: ${{ github.event.pull_request.node_id }}
        run: |
          PROJECT_ID=$(gh api graphql -f query='query($login:String!,$number:Int!){ user(login:$login){ projectV2(number:$number){ id }}}' -f login="$OWNER" -F number="$PROJ_NUM" --jq '.data.user.projectV2.id')
          if [ "$EVENT" = "issues" ]; then CONTENT="$ISSUE_NODE"; else CONTENT="$PR_NODE"; fi
          gh api graphql -f query='mutation($project:ID!,$content:ID!){ addProjectV2ItemById(input:{projectId:$project, contentId:$content}){ item { id } } }' -F project="$PROJECT_ID" -F content="$CONTENT"
