name: Pages (static preview)
on:
  pull_request:
    paths: ["site/**",".github/workflows/pages.yml"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: mkdir -p _site && shopt -s dotglob || true; cp -r site/* _site/ 2>/dev/null || true
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./_site }
  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with: { preview: true }
